#!/usr/bin/env node
// Bundles the brand's Google Fonts OFFLINE for isolated (network-off) rendering. Fetches each font's
// CSS, inlines every woff2 as a base64 data-URI, and writes src/remotion/fonts-local.css. The render
// (server/render) imports that CSS so no gstatic fetch happens at render time. Re-run if fonts change:
//   node tools/fetch-fonts.mjs
import { writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const FAMILIES = [
  "Space+Grotesk:wght@500;600;700",
  "Inter:wght@400;500;600",
  "Plus+Jakarta+Sans:wght@500;600",
  "JetBrains+Mono:wght@400;500",
];
// a desktop UA → Google returns woff2 (not the legacy formats)
const UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const KEEP = new Set(["latin", "latin-ext"]); // English + German; drop cyrillic/greek/vietnamese
let css = "/* offline-bundled brand fonts — generated by tools/fetch-fonts.mjs (do not edit) */\n";
let count = 0;
for (const fam of FAMILIES) {
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${fam}&display=swap`, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`font css ${fam}: ${res.status}`);
  const text = await res.text();
  // each @font-face is preceded by a /* subset */ comment — keep only latin / latin-ext
  for (const m of text.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)) {
    if (!KEEP.has(m[1])) continue;
    let block = m[2];
    const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    if (url) {
      const r = await fetch(url, { headers: { "User-Agent": UA } });
      if (!r.ok) throw new Error(`woff2 ${url}: ${r.status}`);
      const b64 = Buffer.from(await r.arrayBuffer()).toString("base64");
      block = block.replace(url, `data:font/woff2;base64,${b64}`);
      count++;
    }
    css += `/* ${m[1]} */\n${block}\n`;
  }
}
const out = join(ROOT, "src", "remotion", "fonts-local.css");
await writeFile(out, css);
console.log(`✔ wrote src/remotion/fonts-local.css (${count} woff2 inlined, ${(css.length / 1024).toFixed(0)} KB)`);
